SOURCE_TYPE_CONGRESSIONAL_HOUSE_PTR = "congressional_house_ptr"
MIN_SUPPORTED_CONGRESSIONAL_YEAR = 2026

PUBLICATION_STATUS_DRAFT = "draft"
PUBLICATION_STATUS_PUBLISHED = "published"
PUBLICATION_STATUS_FAILED_VALIDATION = "failed_validation"
PUBLICATION_STATUS_ARCHIVED = "archived"

DOMAIN_RELEASE_DEVELOPMENT = "development"
DOMAIN_RELEASE_ADMIN_PREVIEW = "admin_preview"
DOMAIN_RELEASE_PUBLISHED = "published"
DOMAIN_RELEASE_DISABLED = "disabled"

TRANSACTION_TYPE_PURCHASE = "purchase"
TRANSACTION_TYPE_SALE = "sale"
TRANSACTION_TYPE_EXCHANGE = "exchange"
TRANSACTION_TYPE_OTHER = "other"
TRANSACTION_TYPE_UNKNOWN = "unknown"

ASSET_TYPE_STOCK = "stock"
ASSET_TYPE_GOVERNMENT_SECURITY = "government_security"
ASSET_TYPE_MUTUAL_FUND = "mutual_fund"
ASSET_TYPE_ETF = "etf"
ASSET_TYPE_BOND = "bond"
ASSET_TYPE_OPTION = "option"
ASSET_TYPE_OTHER = "other"
ASSET_TYPE_UNKNOWN = "unknown"

OWNER_TYPE_SELF = "self"
OWNER_TYPE_SPOUSE = "spouse"
OWNER_TYPE_DEPENDENT_CHILD = "dependent_child"
OWNER_TYPE_JOINT = "joint"
OWNER_TYPE_OTHER = "other"
OWNER_TYPE_UNKNOWN = "unknown"

CANONICAL_TRANSACTION_TYPES = {
    TRANSACTION_TYPE_PURCHASE,
    TRANSACTION_TYPE_SALE,
    TRANSACTION_TYPE_EXCHANGE,
    TRANSACTION_TYPE_OTHER,
    TRANSACTION_TYPE_UNKNOWN,
}

CANONICAL_ASSET_TYPES = {
    ASSET_TYPE_STOCK,
    ASSET_TYPE_GOVERNMENT_SECURITY,
    ASSET_TYPE_MUTUAL_FUND,
    ASSET_TYPE_ETF,
    ASSET_TYPE_BOND,
    ASSET_TYPE_OPTION,
    ASSET_TYPE_OTHER,
    ASSET_TYPE_UNKNOWN,
}

CANONICAL_OWNER_TYPES = {
    OWNER_TYPE_SELF,
    OWNER_TYPE_SPOUSE,
    OWNER_TYPE_DEPENDENT_CHILD,
    OWNER_TYPE_JOINT,
    OWNER_TYPE_OTHER,
    OWNER_TYPE_UNKNOWN,
}
